server:
  port: 8080

logging:
  level:
    org.springframework.web: INFO
    ru.unit_techno.qr_entry_control_imp: INFO

spring:
  application:
    name: qr-entry-control
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: qr_entry_control
        use_sql_comments: true
        format_sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/unit_techno?currentSchema=qr_entry_control
    username: qr_entry_admin
    password: squd
  thymeleaf:
    encoding: UTF-8
  mail:
    host: smtp.yandex.ru
    port: 465
    username: crime-it-tech-user@yandex.ru
    password: jrRJnutB0t
    properties:
      mail:
        debug: true
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true

qr-entry-control:
  comport-name: "COM4"
  cron:
    #real cron "0 0 0 * * *"  real timezone "Europe/Moscow"
    delete-expired-qr-job: "*/30 * * * * *"
    time-zone: "Europe/Moscow"
