server:
  port: 8080

logging:
  level:
    org.springframework.web: INFO
    ru.unit_techno.qr_entry_control_imp: INFO


spring:
  application:
    name: qr-entry-control
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: qr_entry_control
        use_sql_comments: true
        format_sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/unit_techno?currentSchema=qr_entry_control
    username: qr_entry_admin
    password: squd